### ISSUE TITLE
Error when I use /mv reload of MultiverseCore

### ISSUE THREAD

**Issue by Fredh1000** [hpfxd/PandaSpigot#151]
If I use the command /mv reload of the plugin MultiverseCore (version compatible with 1.8.8) it give me this error, and when I left the server, the server crash.

Error:
[19:27:03] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_361]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_361]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:12) ~[patched_1.8.8.jar:git-PandaSpigot-111]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:881) ~[patched_1.8.8.jar:git-PandaSpigot-111]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:412) ~[patched_1.8.8.jar:git-PandaSpigot-111]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:815) ~[patched_1.8.8.jar:git-PandaSpigot-111]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:648) ~[patched_1.8.8.jar:git-PandaSpigot-111]
	at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:133) ~[patched_1.8.8.jar:git-PandaSpigot-111]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_361]
Caused by: java.lang.NullPointerException
	at org.bukkit.event.world.ChunkEvent.<init>(ChunkEvent.java:12) ~[patched_1.8.8.jar:git-PandaSpigot-111]
	at io.papermc.paper.event.packet.PlayerChunkUnloadEvent.<init>(PlayerChunkUnloadEvent.java:20) ~[patched_1.8.8.jar:git-PandaSpigot-111]
	at net.minecraft.server.v1_8_R3.PlayerChunkMap$PlayerChunk.b(PlayerChunkMap.java:431) ~[patched_1.8.8.jar:git-PandaSpigot-111]
	at net.minecraft.server.v1_8_R3.PlayerChunkMap.movePlayer(PlayerChunkMap.java:247) ~[patched_1.8.8.jar:git-PandaSpigot-111]
	at net.minecraft.server.v1_8_R3.PlayerList.d(PlayerList.java:359) ~[patched_1.8.8.jar:git-PandaSpigot-111]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:472) ~[patched_1.8.8.jar:git-PandaSpigot-111]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(PacketPlayInFlying.java:19) ~[patched_1.8.8.jar:git-PandaSpigot-111]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPosition.a(PacketPlayInFlying.java:85) ~[patched_1.8.8.jar:git-PandaSpigot-111]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(PlayerConnectionUtils.java:9) ~[patched_1.8.8.jar:git-PandaSpigot-111]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_361]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_361]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:11) ~[patched_1.8.8.jar:git-PandaSpigot-111]
	... 6 more

Crash report: 
[crash-2023-07-09_19.27.16-server.txt](https://github.com/hpfxd/PandaSpigot/files/11995750/crash-2023-07-09_19.27.16-server.txt)

**Comment by HanielCota** [comment]
IThis seems to me to be a Multiverse Core problem, not Panda's

**Comment by Fredh1000** [comment]
If I use any other fork, this problem doesn't happens.

**Comment by jose27iwnl** [comment]
Please try this version of multiverse core

https://dev.bukkit.org/projects/multiverse-core/files/2428161

**Comment by f3f5-dev** [comment]
for me i dont see errors for this , needs to close this isses

**Comment by MachineBreaker** [comment]
Looks like a problem in a PandaSpigot event implementaiton

**Comment by jose27iwnl** [comment]
Feedback?
