### ISSUE TITLE
its possible to fix this error only editing the jar?

### ISSUE THREAD

**Issue by Kazhuizao** [hpfxd/PandaSpigot#158]
[12:59:43 INFO]: [mcMMOHorse] Enabling mcMMOHorse v4.3.58
[12:59:43 WARN]: java.io.IOException: No such file or directory
[12:59:43 WARN]:        at java.io.UnixFileSystem.createFileExclusively(Native Method)
[12:59:43 WARN]:        at java.io.File.createNewFile(File.java:1023)
[12:59:43 WARN]:        at com.blueskullgames.horserpg.configs.HorseConfigHandler.<init>(HorseConfigHandler.java:36)
[12:59:43 WARN]:        at com.blueskullgames.horserpg.HorseRPG.onEnable(HorseRPG.java:1692)
[12:59:43 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[12:59:43 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[12:59:43 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:454)
[12:59:43 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:393)
[12:59:43 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:352)
[12:59:43 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:439)
[12:59:43 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:403)
[12:59:43 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:358)
[12:59:43 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:301)
[12:59:43 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:603)
[12:59:43 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:133)
[12:59:43 WARN]:        at java.lang.Thread.run(Thread.java:748)
[12:59:43 ERROR]: [mcMMOHorse] Plugin mcMMOHorse v4.3.58 has failed to register events for class com.blueskullgames.horserpg.listeners.HorseListener because org/bukkit/event/entity/EntityBreedEvent does not exist.

**Comment by codemarked** [comment]
As you can see it's the "horse" plugin trying to load a config file that doesn't exist, so contact the plugin developer about it...

**Comment by uRyanxD** [comment]
Closing the issue since as mentioned above it is a problem with the McMMOHorse plugin.
