### ISSUE TITLE
Citizen don't work and generate error

### ISSUE THREAD

**Issue by failaxite** [hpfxd/PandaSpigot#161]
Good morning ! I'm doing this issue to see if it would be possible to fix the errors generated in connection with the Citizen plugin.
I saw that there had already been issues concerning this but I have no idea if in the end it was fixed or not.
I currently have citizen version v2.0.26-SNAPSHOT (build 1822) and here is the error:

[15:44:33] [Server thread/WARN]: [Citizens] Task #48 for Citizens v2.0.26-SNAPSHOT (build 1822) generated an exception
java.lang.NullPointerException: metadata
at io.netty.util.internal.ObjectUtil.checkNotNull(ObjectUtil.java:39) ~[spigot.jar:]
at io.netty.channel.DefaultChannelConfig.setRecvByteBufAllocator(DefaultChannelConfig.java:325) ~[spigot.jar:]
at io.netty.channel.DefaultChannelConfig.<init>(DefaultChannelConfig.java:79) ~[spigot.jar:]
at io.netty.channel.DefaultChannelConfig.<init>(DefaultChannelConfig.java:75) ~[spigot.jar:]
at net.citizensnpcs.nms.v1_8_R3.network.EmptyChannel.<init>(EmptyChannel.java:14) ~[?:?]
at net.citizensnpcs.nms.v1_8_R3.util.NMSImpl.initNetworkManager(NMSImpl.java:1216) ~[?:?]
at net.citizensnpcs.nms.v1_8_R3.network.EmptyNetworkManager.<init>(EmptyNetworkManager.java:12) ~[?:?]
at net.citizensnpcs.nms.v1_8_R3.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:246) ~[?:?]
at net.citizensnpcs.nms.v1_8_R3.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:81) ~[?:?]
at net.citizensnpcs.nms.v1_8_R3.entity.HumanController.createEntity(HumanController.java:52) ~[?:?]
at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41) ~[?:?]
at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:237) ~[?:?]
at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:155) ~[?:?]
at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59) ~[?:?]
at net.citizensnpcs.Citizens$3.run(Citizens.java:332) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:65) ~[spigot.jar:]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:403) ~[spigot.jar:]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:927) ~[spigot.jar:]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:454) ~[spigot.jar:]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:854) ~[spigot.jar:]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:707) ~[spigot.jar:]
at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_292]

Thank you in advance and I remain at your disposal for other details or opinions.

**Comment by uRyanxD** [comment]
Try updating Citizens to the latest build

**Comment by failaxite** [comment]
I just did it and it actually works my bad, thank you!
