### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Regomy** [hpfxd/PandaSpigot#165]
[07:25:51 WARN]: Failed to handle packet for /ip:port
java.lang.IllegalArgumentException: arraySize cannot be negative but was: -1
        at com.google.common.collect.CollectPreconditions.checkNonnegative(CollectPreconditions.java:39) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at com.google.common.collect.Lists.computeArrayListCapacity(Lists.java:119) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at com.google.common.collect.Lists.newArrayListWithExpectedSize(Lists.java:208) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:329) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:172) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:150) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:60) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:461) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:183) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:1017) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:412) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:815) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:648) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:133) ~[patched_1.8.8.jar:git-PandaSpigot-114]
        at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by jose27iwnl** [comment]
When does this happen? Is it fixed?

**Comment by uRyanxD** [comment]
No, @Regomy do you remember how the error occurred?

**Comment by uRyanxD** [comment]
Closing this issue due to lack of response from the issue creator.
