### ISSUE TITLE
Error EssentialsX help

### ISSUE THREAD

**Issue by ShizenXD** [hpfxd/PandaSpigot#169]
[20:11:58 INFO]: [Essentials] Enabling Essentials v2.20.1
[20:11:58 WARN]: java.lang.NullPointerException
[20:11:58 WARN]:        at net.ess3.nms.refl.providers.ReflFormattedCommandAliasProvider.<init>(ReflFormattedCommandAliasProvider.java:39)
[20:11:58 WARN]:        at com.earth2me.essentials.Essentials.onEnable(Essentials.java:420)
[20:11:58 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[20:11:58 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[20:11:58 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:454)
[20:11:58 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:393)
[20:11:58 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:352)
[20:11:58 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:439)
[20:11:58 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:403)
[20:11:58 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:358)
[20:11:58 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:301)
[20:11:58 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:603)
[20:11:58 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:133)
[20:11:58 WARN]:        at java.lang.Thread.run(Unknown Source)
[20:11:58 INFO]: Loaded 853 items from items.csv.
[20:11:58 INFO]: Using locale pt_BR

**Comment by ShizenXD** [comment]
esse erro só ocorre no PandaSpigot, eu testei em diversas forks, a mesma coisa acontece com meu SirVip, e EconomyShopGui

**Comment by uRyanxD** [comment]
I found the problem
