### ISSUE TITLE
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()

### ISSUE THREAD

**Issue by victortedesco** [hpfxd/PandaSpigot#174]
[15:39:28 WARN]: org.apache.commons.lang.UnhandledException: Plugin ChestShop v3.8.12 generated an exception while executing task 122
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
        at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
        at com.Acrobot.ChestShop.Metrics.postPlugin(Metrics.java:335)
        at com.Acrobot.ChestShop.Metrics.access$400(Metrics.java:57)
        at com.Acrobot.ChestShop.Metrics$1.run(Metrics.java:223)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 4 more
        
This only happens with PandaSpigot, on vanilla Paper everything works fine.

**Comment by andreasdc** [comment]
> ChestShop

It shouldn't break the plugin, you can try to disable metrics, I don't see this version on github.

**Comment by victortedesco** [comment]
https://github.com/hpfxd/PandaSpigot/blob/c105f01a66997ac770dc2c59a18852950938d66c/patches/server/0049-Metrics.patch#L130C4-L144C4

Wasn't this made to solve this problem?

**Comment by liorsl** [comment]
The patch you sent seems to modify the built in metrics class, but your plugin seems to be using its own which doesn't properly support 1.8.

**Comment by uRyanxD** [comment]
This error is caused due to the removal of legacy methods (from 1.6 probably), a more technical explanation [here](https://github.com/hpfxd/PandaSpigot/issues/7#issuecomment-1127025213). There's nothing I can do unless @hpfxd decides to re-add the legacy mappings.
