### ISSUE TITLE
ServerConnect error

### ISSUE THREAD

**Issue by gitcarlx** [hpfxd/PandaSpigot#178]
[ServerConnect] Task #16 for ServerConnect v0.1 generated an exception
java.lang.NoSuchMethodError: 'org.bukkit.entity.Player[] org.bukkit.Bukkit.getOnlinePlayers()'
        at com.gmail.emiel.topixx.ServerConnect$1.run(ServerConnect.java:50) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[patched_1.8.8
pigot-116]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftSchedule
atched_1.8.8.jar:git-PandaSpigot-116]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:890) ~[patched_1.8.8.
igot-116]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:412) ~[patched_1.8.8.
igot-116]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:815) ~[patched_1.8.8.
igot-116]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:648) ~[patched_1.8.
Spigot-116]
        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:133) ~[pa
:git-PandaSpigot-116]
        at java.lang.Thread.run(Thread.java:842) [?:?]

**Comment by uRyanxD** [comment]
See [this](https://github.com/hpfxd/PandaSpigot/issues/174#issuecomment-1984559629)
