### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by zakmacho** [hpfxd/PandaSpigot#184]
sends every 2 mins
[12:12:22 WARN]: Exception in thread "Craft Scheduler Thread - 326" 
[12:12:22 WARN]: org.apache.commons.lang.UnhandledException: Plugin Multiverse-Core v2.5-b699 generated an exception while executing task 33
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
        at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
        at org.mcstats.multiverse.Metrics.postPlugin(Metrics.java:357)
        at org.mcstats.multiverse.Metrics.access$400(Metrics.java:64)
        at org.mcstats.multiverse.Metrics$1.run(Metrics.java:245)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 4 more

**Comment by uRyanxD** [comment]
Use this version of MultiverseCore: https://dev.bukkit.org/projects/multiverse-core/files/2428161
