### ISSUE TITLE
SkinRestorer 

### ISSUE THREAD

**Issue by HanielCota** [hpfxd/PandaSpigot#44]
[11:57:24 INFO]: [SkinsRestorer] Enabling SkinsRestorer v14.2.3
[11:57:24 INFO]: [SkinsRestorer] Detected Minecraft v1_8_R3, using SpigotSkinRefresher.
[11:57:24 WARN]: java.lang.NoSuchMethodException: org.bukkit.Server$Spigot.getPaperConfig()
[11:57:24 WARN]:        at java.lang.Class.getMethod(Class.java:1786)
[11:57:24 WARN]:        at net.skinsrestorer.paper.PaperUtil.getPaperConfig(PaperUtil.java:28)
[11:57:24 WARN]:        at net.skinsrestorer.bukkit.SkinsRestorer.checkProxyMode(SkinsRestorer.java:416)
[11:57:24 WARN]:        at net.skinsrestorer.bukkit.SkinsRestorer.pluginStartup(SkinsRestorer.java:205)
[11:57:24 WARN]:        at net.skinsrestorer.bukkit.SkinsRestorer.onEnable(SkinsRestorer.java:144)
[11:57:24 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[11:57:24 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[11:57:24 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:445)
[11:57:24 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
[11:57:24 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
[11:57:24 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:439)
[11:57:24 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:403)
[11:57:24 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:358)
[11:57:24 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:301)
[11:57:24 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:603)
[11:57:24 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:133)
[11:57:24 WARN]:        at java.lang.Thread.run(Thread.java:748)

![Screenshot_1](https://user-images.githubusercontent.com/117860225/202486581-d0efc685-c2c1-410a-9d24-a450e8eb594c.png)

**Comment by uRyanxD** [comment]
I was able to reproduce this error

**Comment by uRyanxD** [comment]
Checking the SkinsRestorer code I realized that it checks through the getPaperConfig() method but this method is called getPaperSpigotConfig() in 1.8 and earlier versions, the strange thing is the code does not return exception when we use paperspigot 1.8 only in PandaSpigot
References: https://github.com/SkinsRestorer/SkinsRestorerX/blob/dev/multiver/paper/src/main/java/net/skinsrestorer/paper/PaperUtil.java#L28
https://github.com/PaperMC/Paper/blob/ver/1.8.8/Spigot-API-Patches/0014-Timings-v2.patch#L2817

**Comment by andreasdc** [comment]
Probably this
https://github.com/SkinsRestorer/SkinsRestorerX/blob/22a8ed9d452c52afe793d9f565574031abafe31f/bukkit/src/main/java/net/skinsrestorer/bukkit/SkinApplierBukkit.java#L244
returns false and it doesn't check for paper methods

**Comment by uRyanxD** [comment]
We already added a workaround for this some time ago, however I noticed that the "Add Packet Limiter" patch adds the PaperConfig class (from paper 1.9+) SkinRestorer should detect it as if it were in newer versions and throw this error, however, we couldn't delete the class because ViaVersion checks if it exists because of the packet limiter, a possible solution would be to send a pullrequest to SkinsRestorer, checking the panda configuration (https://github.com/ViaVersion/ViaVersion/ blob/ master/bukkit/src/main/java/com/viaversion/viaversion/bukkit/platform/PaperViaInjector.java#L71), however, I don't think it's necessary for now, unless some other plugin has a problem for think it's in newer versions.
