### ISSUE TITLE
Compatibility error with Citizens

### ISSUE THREAD

**Issue by MaxedOut1** [hpfxd/PandaSpigot#78]
Everytime when starting the server I get the below error, this error causes npcs to not load into the world. This does not happen when running the server with regular paper. This happens right at the end of server start up.

```
[10:16:41 WARN]: [Citizens] Task #20 for Citizens v2.0.28-SNAPSHOT (build 2386) generated an exception
java.lang.NullPointerException: metadata
        at io.netty.util.internal.ObjectUtil.checkNotNull(ObjectUtil.java:39) ~[patched_1.8.8.jar:git-PandaSpigot-79]
        at io.netty.channel.DefaultChannelConfig.setRecvByteBufAllocator(DefaultChannelConfig.java:325) ~[patched_1.8.8.jar:git-PandaSpigot-79]
        at io.netty.channel.DefaultChannelConfig.<init>(DefaultChannelConfig.java:79) ~[patched_1.8.8.jar:git-PandaSpigot-79]
        at io.netty.channel.DefaultChannelConfig.<init>(DefaultChannelConfig.java:75) ~[patched_1.8.8.jar:git-PandaSpigot-79]
        at net.citizensnpcs.nms.v1_8_R3.network.EmptyChannel.<init>(EmptyChannel.java:14) ~[?:?]
        at net.citizensnpcs.nms.v1_8_R3.util.NMSImpl.initNetworkManager(NMSImpl.java:1333) ~[?:?]
        at net.citizensnpcs.nms.v1_8_R3.network.EmptyNetworkManager.<init>(EmptyNetworkManager.java:12) ~[?:?]
        at net.citizensnpcs.nms.v1_8_R3.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:246) ~[?:?]
        at net.citizensnpcs.nms.v1_8_R3.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:82) ~[?:?]
        at net.citizensnpcs.nms.v1_8_R3.entity.HumanController.createEntity(HumanController.java:54) ~[?:?]
        at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:255) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:160) ~[?:?]
        at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59) ~[?:?]
        at net.citizensnpcs.Citizens$CitizensLoadTask.run(Citizens.java:510) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[patched_1.8.8.jar:git-PandaSpigot-79]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) ~[patched_1.8.8.jar:git-PandaSpigot-79]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:889) ~[patched_1.8.8.jar:git-PandaSpigot-79]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:412) ~[patched_1.8.8.jar:git-PandaSpigot-79]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:814) ~[patched_1.8.8.jar:git-PandaSpigot-79]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:647) ~[patched_1.8.8.jar:git-PandaSpigot-79]
        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:133) ~[patched_1.8.8.jar:git-PandaSpigot-79]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_291]

```

**Comment by MaxedOut1** [comment]
It appears I wass running an old citizens version. This error does not appear on newer versions

**Comment by mechoriet** [comment]
"old" more an ancient version 😄
