### ISSUE TITLE
ERRO PANDASPIGOT!

### ISSUE THREAD

**Issue by Nyeamura01** [hpfxd/PandaSpigot#86]
15:57:31 INFO]: TPS from last 1m, 5m, 15m: *20.0, *20.0, *20.0
[15:57:39 INFO]: This server is running PandaSpigot version git-PandaSpigot-82 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT) (Git: 8da11b5)
[15:57:39 INFO]: Checking version, please wait...
[15:57:39 WARN]: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/repos/hpfxd/PandaSpigot/actions/workflows/build.yml/runs
[15:57:39 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[15:57:39 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[15:57:39 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[15:57:39 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[15:57:39 WARN]:        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1947)
[15:57:39 WARN]:        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1942)
[15:57:39 WARN]:        at java.security.AccessController.doPrivileged(Native Method)
[15:57:39 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1941)
[15:57:39 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1511)
[15:57:39 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1495)
[15:57:39 WARN]:        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
[15:57:39 WARN]:        at org.bukkit.command.defaults.VersionCommand.fetchActionsDistance(VersionCommand.java:284)
[15:57:39 WARN]:        at org.bukkit.command.defaults.VersionCommand.obtainVersion(VersionCommand.java:195)
[15:57:39 WARN]:        at org.bukkit.command.defaults.VersionCommand.access$000(VersionCommand.java:33)
[15:57:39 WARN]:        at org.bukkit.command.defaults.VersionCommand$1.run(VersionCommand.java:178)
[15:57:39 WARN]:        at java.lang.Thread.run(Thread.java:748)
[15:57:39 WARN]: Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/repos/hpfxd/PandaSpigot/actions/workflows/build.yml/runs
[15:57:39 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1897)
[15:57:39 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1495)
[15:57:39 WARN]:        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
[15:57:39 WARN]:        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352)
[15:57:39 WARN]:        at org.bukkit.command.defaults.VersionCommand.fetchActionsDistance(VersionCommand.java:283)
[15:57:39 WARN]:        ... 4 more
[15:57:39 INFO]: Error obtaining version information

[16:13:39 ERROR]: Block at -687,33,338 is MOB_SPAWNER but has net.minecraft.server.v1_8_R3.TileEntityChest@5400ba1f. Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.

It is not generating monsters on the map and /version generating error

**Comment by mechoriet** [comment]
the version command for sure must be github messing with the api and breaking something cause testing same version at 01:37 UTC+2  it just return the normal "You are running the latest version"

for the second part more information is needed what is the situation of the server plugins configs of spigot/bukkit/paper/pandaspigot yml

**Comment by Nyeamura01** [comment]
the config is all standard, I didn't touch anything, pandaspigot is giving these errors with the config already standard

**Comment by mechoriet** [comment]
Latest version 83 solved the spawning part the second part is strange cause it always works for me

**Comment by iamnoksio** [comment]
java.io.IOException: Server returned HTTP response code: 403 for URL:

**Comment by mechoriet** [comment]
gonna gamble on it being github api that was broken at that point in time
since we haven't heard any other reports of this kind
